---
address_objects:
  - name: BRANCH_USERS_SUBNET
    value: 10.20.20.0/24
    description: Branch  internal users subnet

  - name: BRANCH_DMZ_SUBNET
    value: 200.200.200.0/24
    description: Branch DMZ Subnet

security_rules:
  - name: ALLOW-BRANCH-USERS-OUTBOUND
    source_zone:
      - User
    destination_zone:
      - Untrust
    source_ip:
      - BRANCH_USERS_SUBNET
    destination_ip:
      - any
    application:
      - any
    service:
      - application-default
    action: allow
    log_end: true
    description: allow User zone to Untrust

  - name: ALLOW-BRANCH-USERS-TO-DMZ
    source_zone:
      - User
    destination_zone:
      - DMZ
    source_ip:
      - BRANCH_USERS_SUBNET
    destination_ip:
      - BRANCH_DMZ_SUBNET
    application:
      - ping
      - ssh
      - web-browsing
      - ssl
    service:
      - application-default
    action: allow
    log_end: true
    description: Allow Branch users to DMZ server
  - name: ALLOW-BRANCH-USERS-TO-VPN
    source_zone:
      - User
    destination_zone:
      - VPN
    source_ip:
      - BRANCH_USERS_SUBNET
    destination_ip:
      - any
    application:
      - any
    service:
      - application-default
    action: allow
    log_end: true
    description: allow User zone to VPN
nat_rules:
  - name: SNAT-BRANCH-USERS-OUTBOUND
    from_zones:
      - User
    to_zones:
      - Untrust
    source_addresses:
      - BRANCH_USERS_SUBNET
    destination_addresses:
      - any
    service: any
    source_translation_type: dynamic-ip-and-port
    source_translation_address_type: interface-address
    source_translation_interface: ethernet1/1
    description: Source NAT Branch users to untrustt

tunnel:
  - name: tunnel_for_ipsec
    tunnel_interface: tunnel.1
    virtual_router: default
    tunnel_ip: 172.16.1.2/30
    vpn_zone: VPN
    description: "ipsec tunnel"

ike_profile:
  - name: Ike_profile
    dh_group: group5
    auth_algorithm: md5
    encryption: aes-256-cbc

ipsec_profile:
  - name: Ipsec_profile
    ipsec_auth: sha256
    encryption: aes-256-cbc
    group: group14

ike_gateway:
  - gateway_name: Ike_gateway
    gateway_version: ikev2
    gateway_interface: ethernet1/1
    ike_peer_ip: 57.57.57.57
    ike_key: Muiefane123
    ike_profile: Ike_profile

ipsec_to_ike:
  - tunnel_name: IPSEC_to_HQ
    tunnel_interface: tunnel.1
    ike_gateway: Ike_gateway
    ipsec_profile: Ipsec_profile
