---
address_objects:
  - name: HQ_USERS_SUBNET
    value: 10.10.10.0/24
    description: HQ internal users subnet

  - name: HQ_DMZ_SUBNET
    value: 100.100.100.0/24
    description: HQ DMZ Subnet

security_rules:
  - name: ALLOW-HQ-USERS-OUTBOUND
    source_zone:
      - User
    destination_zone:
      - Untrust
    source_ip:
      - HQ_USERS_SUBNET
    destination_ip:
      - any
    application:
      - any
    service:
      - application-default
    action: allow
    log_end: true
    description: allow User zone to Untrust
  
  - name: ALLOW-HQ-USERS-TO-DMZ
    source_zone:
      - User
    destination_zone:
      - DMZ
    source_ip:
      - HQ_USERS_SUBNET
    destination_ip:
      - HQ_DMZ_SUBNET
    application:
      - ping
      - ssh
      - web-browsing
      - ssl
    service:
      - application-default
    action: allow
    log_end: true
    description: Allow HQ users to DMZ server
  - name: ALLOW-HQ-USERS-TO-VPN
    source_zone:
      - User
    destination_zone:
      - VPN
    source_ip:
      - HQ_USERS_SUBNET
    destination_ip:
      - any
    application:
      - any
    service:
      - application-default
    action: allow
    log_end: true
    description: allow User zone to VPN
nat_rules:
  - name: SNAT-HQ-USERS-OUTBOUND
    from_zones:
      - User
    to_zones:
      - Untrust
    source_addresses:
      - HQ_USERS_SUBNET
    destination_addresses:
      - any
    service: any
    source_translation_type: dynamic-ip-and-port
    source_translation_address_type: interface-address
    source_translation_interface: ethernet1/1
    description: Source NAT HQ users to Untrust

tunnel:
  - name : tunnel_for_ipsec
    tunnel_interface: tunnel.1
    virtual_router: default
    tunnel_ip: 172.16.1.1/30
    vpn_zone: VPN
    description: "ipsec tunnel"

ike_profile:
  - name: Ike_profile
    dh_group:  group5
    auth_algorithm:  md5 
    encryption:   aes-256-cbc

ipsec_profile:
  - name : Ipsec_profile
    ipsec_auth: sha256
    encryption: aes-256-cbc
    group: group14

ike_gateway:
  - gateway_name: Ike_gateway
    gateway_version: ikev2
    gateway_interface: ethernet1/1
    ike_peer_ip: 58.58.58.58
    ike_key: Muiefane123
    ike_profile: Ike_profile

ipsec_to_ike:
  - tunnel_name: IPSEC_to_HQ
    tunnel_interface: tunnel.1
    ike_gateway: Ike_gateway
    ipsec_profile: Ipsec_profile