---
all:
  children:
    staging:
      children:
        providers:
          hosts:
            stg-isp1:
              ansible_host: 192.168.116.106
            stg-isp2:
              ansible_host: 192.168.116.110

        enterprise:
          hosts:
            stg-edge1:
              ansible_host: 192.168.116.107
            stg-core:
              ansible_host: 192.168.116.108
            stg-edge2:
              ansible_host: 192.168.116.109

  vars:
    ansible_user: admin
    ansible_password: admin123
    ansible_network_os: cisco.ios.ios
    ansible_connection: ansible.netcommon.network_cli
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: admin123
