---
all:
  children:
    production:
      children:
        providers:
          hosts:
            prd-isp1:
              ansible_host: 192.168.116.101
            prd-isp2:
              ansible_host: 192.168.116.105

        enterprise:
          hosts:
            prd-edge1:
              ansible_host: 192.168.116.102
            prd-core:
              ansible_host: 192.168.116.103
            prd-edge2:
              ansible_host: 192.168.116.104

  vars:
    ansible_user: admin
    ansible_password: admin123
    ansible_network_os: cisco.ios.ios
    ansible_connection: ansible.netcommon.network_cli

