---
- name: Test version
  hosts: cisco 
  gather_facts: no

  tasks:
    - name: set loop 0
      cisco.ios.ios_config:
        lines:
          - interface loopback {{ item.id }}
          - ip address {{ item.ip }} {{ item.mask }}
      with_items: "{{ loopbacks }}"
