---
- name: Test version
  hosts: cisco 
  gather_facts: no

  tasks:
    - name: Show version
      cisco.ios.ios_command:
        commands:
          - show version
          - show inventory 
      register: output 

    - name : Print
      debug:
        var: output.stdout_lines
    