- name: Add IPSec crypto config to the firewall
  paloaltonetworks.panos.panos_ipsec_profile:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
    state: 'present'
    name: "{{item.name}}"
    esp_authentication: "{{ item.ipsec_auth}}"
    esp_encryption: "{{ item.encryption }}"
    lifetime_seconds: '3600'
    dh_group: "{{item.group}}"
  loop: "{{ ipsec_profile }}"
  register: ipsec_profile_result