vlans:
  - number: 10
    description: sales
  - number: 20
    description: accounting 

accessports:
  - name: GigabitEthernet0/3
    description: Access_port_in_sales_vlan
    vlan: 10

  - name: GigabitEthernet1/0
    description: Access_port_in_accounting_vlan
    vlan: 20

trunks:
  - name: GigabitEthernet0/0
    description: Trunk_to_Distr1
    allowed: 10,20

  - name: GigabitEthernet0/1
    description: Trunk_to_Distr2
    allowed: 10,20
    