vlans:
  - number: 30
    description: HR
  - number: 40
    description: guest

accessports:
  - name: GigabitEthernet0/3
    description: Access_port_in_HR_vlan
    vlan: 30

  - name: GigabitEthernet1/0
    description: Access_port_in_guest_vlan
    vlan: 40

trunks:
  - name: GigabitEthernet0/0
    description: Trunk_to_Distr2
    allowed: 30,40

  - name: GigabitEthernet0/1
    description: Trunk_to_Distr1
    allowed: 30,40
    